server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hb
    username: root
    password: mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Options: none, update, create, create-drop
    show-sql: true      # To log SQL statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # For MySQL 8.x
        format_sql: true
  sql:
    init:
      mode: always  # To run SQL scripts on startup
